services:
  - type: web
    name: blog-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://rakibulrifat44:vwMOler3uiUeDGbi@cluster0.nnzct3e.mongodb.net/blogdb?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000
